export const START_FETCH_MOVIES = "START_FETCH_MOVIES";
export const SUCCESS_FETCH_MOVIES = "SUCCESS_FETCH_MOVIES";
export const FAILED_FETCH_MOVIES = "FAILED_FETCH_MOVIES";

export const START_FETCH_NEXT_MOVIES = "START_FETCH_NEXT_MOVIES";
export const SUCCESS_FETCH_NEXT_MOVIES = "SUCCESS_FETCH_NEXT_MOVIES";
export const FAILED_FETCH_NEXT_MOVIES = "FAILED_FETCH_NEXT_MOVIES";

export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD";
